# Generated by Django 3.2.5 on 2021-08-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='item_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='listing_img'),
        ),
    ]
