# Generated by Django 3.2.5 on 2021-08-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210821_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='item_image',
            field=models.ImageField(default='default.jpg', upload_to='listing_img'),
        ),
    ]
