# Generated by Django 3.2.5 on 2021-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('default', 'Select Category'), ('electronics', 'Electronics'), ('fabric', 'Fabric'), ('consumable', 'Consumable'), ('estate', 'Estate'), ('othes', 'Others')], default='default', max_length=100),
        ),
    ]
