# Generated by Django 3.2.5 on 2021-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211019_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_liked', to='network.Post'),
        ),
    ]
