# Generated by Django 3.2.5 on 2021-10-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_user_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlike',
        ),
    ]
