# Generated by Django 3.2 on 2022-01-29 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
