# Generated by Django 3.2 on 2022-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20220129_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
